Export env vars

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -49,6 +49,12 @@ $JBOSS_HOME/bin/jboss-cli.sh --connect --command="/subsystem=datasources:install
 
 # 4) install datasource
 echo "-----> install data source ... "
+
+for KEY in PGUSER PGPASSWORD PGHOST PGDATABASE; do
+  [ -f $ENV_DIR/$KEY ] && export "$KEY=$(cat $ENV_DIR/$KEY)"
+  [ -z "${!KEY}" ] && echo "You didn't set $KEY, and this is required." && exit 1
+done
+
 echo $PGHOST
 echo $PGDATABASE
 $JBOSS_HOME/bin/jboss-cli.sh --connect --command="data-source add --name=smartIDDataSource --driver-name=postgresql --jndi-name=java:/smartIDDataSource --driver-class=org.postgresql.Driver --user-name=$PGUSER --password=$PGPASSWORD --connection-url=jdbc:postgres://$PGHOST:5432/$PGDATABASE"
